### ISSUE TITLE
trev lists all tasks in ID order

### ISSUE THREAD

**Issue by linuxcaffe** [nocejo/trev#40]
Very strange thing; in the most recent update of trev (and also the previous version) when I run trev.pl, it lists every pending task in order of ID, with each action. Using different reports in the command invocation
<pre>
trev.pl list
</pre>
doesn't seem to have an effect, as it used to. "list" is my default command, not using modified trevrc..
Having 180+ tasks scroll past every time is.. less good :)

**Comment by nocejo** [comment]
Thanks for the report.
I'm not been able to reproduce this behavior, but probably trev is reading trevrc in the script directory.
I've reduced the configuration in trevrc to the hard wired defaults and pushed it.
Gonna see if this was the problem.

**Comment by linuxcaffe** [comment]
I might never know what that was,but with current version, the problem went away!

**Comment by nocejo** [comment]
Yes, it must be something concerning trevrc, that has been changed.

This is a problem: I must to have some example trevrc in the repository, and need it to be informative but not harmful, because a user can clone/download it from here and have it affecting the behavior of trev without the user noticing.

Perhaps putting same defaults that hardwired ones and commenting out any other information can be the solution.
